before_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags: 
  - shell-cmd
  - vs2019
  - win2016
  only:
  - master
  script:
  - dotnet restore Diamond.sln --no-cache --verbosity quiet
  - dotnet build Diamond.sln --configuration Release --verbosity minimal

test:
  stage: test
  tags: 
  - shell-cmd
  - vs2019
  - win2016
  only:
  - master
  script:
  - dotnet restore Diamond.sln --no-cache --verbosity quiet
  - dotnet build Diamond.sln --configuration Release --verbosity quiet
  - dotnet test Common.LibTests\Common.LibTests.csproj --configuration Release

deploy:
  stage: deploy
  tags: 
  - shell-cmd
  - vs2019
  - win2016
  only:
  - master
  script:
  - set VERSION=2020.5.7.2
  - dotnet restore Diamond.sln --no-cache --verbosity quiet
  - dotnet build Diamond.sln --configuration Release --verbosity quiet
  - dotnet publish Identity.Web\Identity.Web.csproj --output Identity.Web\bin\Release\netcoreapp3.1\publish --configuration Release
  - dotnet publish STS.Web\STS.Web.csproj --output STS.Web\bin\Release\netcoreapp3.1\publish --configuration Release
  - dotnet publish Games.Web\Games.Web.csproj --output Games.Web\bin\Release\netcoreapp3.1\publish --configuration Release
  - dotnet octo pack --id=Ahfc.WebSvc.Sandbox2.Identity --version=%VERSION% --basePath=Identity.Web\bin\Release\netcoreapp3.1\publish\ --outFolder=.
  - dotnet octo pack --id=Ahfc.WebSvc.Sandbox2.Sts --version=%VERSION% --basePath=STS.Web\bin\Release\netcoreapp3.1\publish\ --outFolder=.
  - dotnet octo pack --id=Ahfc.WebSvc.Sandbox2.Games --version=%VERSION% --basePath=Games.Web\bin\Release\netcoreapp3.1\publish\ --outFolder=.
  - dotnet nuget push *.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
  - set VERSION=
